
# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the "master" branch
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]
on:
  push:
    # branches: [ "master" ]
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Create the release files
        run: find * -maxdepth 0 -type d -exec tar -czf "{}".tar.gz "{}" \;

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.tar.gz"
          # note you'll typically need to create a personal access token
          # with permissions to create releases in the other repo
          token: ${{ secrets.GITHUB_TOKEN }}
